name: "HomeAnalytics Add-on"
description: "A Home Assistant Add-on for home energy consumption and cost analytics"
version: "0.1.13"
slug: "home-analytics"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  8082/tcp: 8082
ingress: true
ingress_port: 8082
panel_icon: mdi:web
panel_title: HomeAnalytics
panel_admin: true
hassio_api: true
homeassistant_api: true
auth_api: true
options:
  influx:
    url: "http://homeassistant.local:8086/api/v2/query"
    username: "your_db_username_here"
    password: "your_db_password_here"
    bucket: "home_assistant/autogen"
  sensors:
    electricity_price: "sensor.electricity_price_gustavsgatan_32a"
    energy_consumption: "sensor.last_meter_consumption_gustavsgatan_32a"
    gardshus: "sensor.energy_meter_total_consumption_gardshus"
    salong: "sensor.energy_meter_total_consumption_lenes_har"
  cost:
    areas:
      gardshus:
        name: "GÃ¥rdshus"
        eon_abonnemang_bidrag_inkl_moms: 165.00
      salong:
        name: "Salong"
        eon_abonnemang_bidrag_inkl_moms: 0
    energy_supplier:
      abonnemang_ex_moms: 39.20
      markup_per_kwh_ex_moms: 0.068
    utility_operator:
      overforingsavgift_per_kwh: 0.2456
      energiskatt_per_kwh: 0.439
      abonnemang_ex_moms: 805.00
    common:
      moms_rate: 0.25

schema:
  influx:
    url: str
    username: str
    password: str
    bucket: str
  sensors:
    electricity_price: str
    energy_consumption: str
    gardshus: str
    salong: str
  cost:
    areas:
      gardshus:
        name: str
        eon_abonnemang_bidrag_inkl_moms: float
      salong:
        name: str
        eon_abonnemang_bidrag_inkl_moms: float
    energy_supplier:
      abonnemang_ex_moms: float
      markup_per_kwh_ex_moms: float
    utility_operator:
      overforingsavgift_per_kwh: float
      energiskatt_per_kwh: float
      abonnemang_ex_moms: float
    common:
      moms_rate: float